; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[libraries]
configmanager = https://github.com/nrwiersma/ConfigManager.git

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_port = /dev/cu.usbserial-0001
upload_port = /dev/cu.usbserial-0001
upload_speed = 921600
monitor_speed = 115200
lib_deps = 
	${libraries.configmanager}
	thijse/ArduinoLog@^1.1.1
	einararnason/ArduinoQueue@^1.2.5
	lsatan/SmartRC-CC1101-Driver-Lib@^2.5.7
	shchuko/rtl_433_ESP@^0.3.2
	sui77/rc-switch@^2.6.4
	jgromes/RadioLib@^5.3.0
build_flags =
    '-D OOK_MODULATION=true'      ; False is FSK, True is OOK
    '-D RF_CC1101="CC1101"'       ; CC1101 Transceiver Module
    '-D RF_MODULE_GDO0=26'        ; CC1101 pin GDO0 Tx
    '-D RF_MODULE_GDO2=27'        ; CC1101 pin GDO2 Rx
    '-D RF_MODULE_FREQ=433.92'      
    '-D RAW_SIGNAL_DEBUG=true'
    '-D DEMOD_DEBUG=true'
    '-D SERVER_URL="http://192.168.2.25:1880/"'
